server:
  port: 8088

spring:
  cloud:
    nacos:
      discovery:
        namespace: dev
        server-addr: 198.211.51.239:8848
        register-enabled: true
        username: nacos
        password: nacos